# Generated by Django 5.1.4 on 2025-01-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_access_level_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
    ]
