# Generated by Django 5.1.4 on 2025-01-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
